name: Manpage
on:
  push:
    branches: [master]
    paths:
      - 'detex.1'
  pull_request:
    paths:
      - 'detex.1'

jobs:
  manpage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Setup dependencies
        run: sudo apt install mandoc
      - run: mandoc -T lint detex.1
