name: Test
on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:

    # https://github.com/actions/runner-images
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            compiler: gcc
            valgrind: true
          - os: ubuntu-latest
            compiler: clang
            valgrind: true
          - os: ubuntu-22.04
            compiler: gcc
            valgrind: false
          - os: ubuntu-22.04
            compiler: clang
            valgrind: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - name: Setup dependencies
        run: sudo apt update && sudo apt install libfl-dev
      - name: Set compiler
        run: |
          export CC=${{matrix.compiler}}
          $CC --version
      - name: Compile and test with valgrind
        if: ${{ matrix.valgrind == true }}
        run: |
          sudo apt install valgrind
          CFLAGS=-g make
          ./test.pl --valgrind
      - name: Compile and test without valgrind
        if: ${{ matrix.valgrind != true }}
        run: |
          make
          ./test.pl
      - name: Test packaging
        if: ${{ matrix.valgrind != true }}
        run: make package
